[features]
seeds = false
skip-lint = false
[programs.localnet]
step_staking_test = "7ZYww9sNB9iJKYCh3LefK2RiczAHddTLZ8dz9SGSfXzJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "/home/dev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
